// ======================================================
// mockData.js - נתוני דמה לפיתוח ובדיקות
// ======================================================
// כאשר מחברים Firebase אמיתי (ראה firebase.js),
// ניתן להשתמש בנתונים אלו לאתחול ראשוני של Firestore:
//
//   import { seedFirestore } from './seedFirestore';
//   seedFirestore(); // הרץ פעם אחת בלבד
// ======================================================

export const mockDrivers = [
  {
    id: "d1",
    name: "משה כהן",
    phone: "0501234567",
    status: "driving",
    currentRouteId: "r1",
    vehicleNumber: "אוטובוס 15",
    lastLogin: new Date(),
  },
  {
    id: "d2",
    name: "דוד לוי",
    phone: "0527654321",
    status: "online",
    currentRouteId: "r2",
    vehicleNumber: "אוטובוס 22",
    lastLogin: new Date(),
  },
  {
    id: "d3",
    name: "יוסף אברהם",
    phone: "0541111222",
    status: "offline",
    currentRouteId: null,
    vehicleNumber: "אוטובוס 7",
    lastLogin: new Date(Date.now() - 3600000),
  },
  {
    id: "d4",
    name: "אמיר בן דוד",
    phone: "0523333444",
    status: "driving",
    currentRouteId: "r3",
    vehicleNumber: "אוטובוס 31",
    lastLogin: new Date(),
  },
  {
    id: "d5",
    name: "רונן שלום",
    phone: "0505555666",
    status: "online",
    currentRouteId: "r4",
    vehicleNumber: "אוטובוס 18",
    lastLogin: new Date(),
  },
  {
    id: "d6",
    name: "ניר גולן",
    phone: "0507777888",
    status: "offline",
    currentRouteId: null,
    vehicleNumber: "אוטובוס 9",
    lastLogin: new Date(Date.now() - 7200000),
  },
];

export const mockRoutes = [
  {
    id: "r1",
    name: "מסלול תל אביב צפון",
    status: "active",
    assignedDriverUid: "d1",
    totalDistance: 22.5,
    schedule: {
      startTime: "07:00",
      endTime: "08:30",
      days: ["א'", "ב'", "ג'", "ד'", "ה'"],
    },
    stops: [
      {
        stopId: "s1",
        name: "תחנה מרכזית צפון",
        address: "דרך נמיר 100, תל אביב",
        lat: 32.1,
        lng: 34.795,
        order: 1,
        estimatedTime: "07:00",
        studentsCount: 18,
      },
      {
        stopId: "s2",
        name: "שדרות נורדאו",
        address: "נורדאו 45, תל אביב",
        lat: 32.092,
        lng: 34.783,
        order: 2,
        estimatedTime: "07:12",
        studentsCount: 12,
      },
      {
        stopId: "s3",
        name: "כיכר דיזנגוף",
        address: "דיזנגוף 50, תל אביב",
        lat: 32.081,
        lng: 34.773,
        order: 3,
        estimatedTime: "07:25",
        studentsCount: 22,
      },
      {
        stopId: "s4",
        name: "בית הספר המרכזי",
        address: "ביאליק 5, רמת גן",
        lat: 32.07,
        lng: 34.811,
        order: 4,
        estimatedTime: "07:45",
        studentsCount: 0,
      },
    ],
  },
  {
    id: "r2",
    name: "מסלול רמת גן–גבעתיים",
    status: "active",
    assignedDriverUid: "d2",
    totalDistance: 15.3,
    schedule: {
      startTime: "07:15",
      endTime: "08:45",
      days: ["א'", "ב'", "ג'", "ד'", "ה'"],
    },
    stops: [
      {
        stopId: "s5",
        name: "עיריית רמת גן",
        address: "ביאליק 1, רמת גן",
        lat: 32.082,
        lng: 34.812,
        order: 1,
        estimatedTime: "07:15",
        studentsCount: 14,
      },
      {
        stopId: "s6",
        name: "גבעתיים מרכז",
        address: "קוסובסקי 20, גבעתיים",
        lat: 32.07,
        lng: 34.81,
        order: 2,
        estimatedTime: "07:30",
        studentsCount: 19,
      },
      {
        stopId: "s7",
        name: "בית הספר המרכזי",
        address: "ביאליק 5, רמת גן",
        lat: 32.07,
        lng: 34.811,
        order: 3,
        estimatedTime: "07:50",
        studentsCount: 0,
      },
    ],
  },
  {
    id: "r3",
    name: "מסלול פתח תקווה",
    status: "delayed",
    assignedDriverUid: "d4",
    totalDistance: 28.7,
    schedule: {
      startTime: "07:00",
      endTime: "08:30",
      days: ["א'", "ב'", "ג'", "ד'", "ה'"],
    },
    stops: [
      {
        stopId: "s8",
        name: "פתח תקווה מרכז",
        address: "הרצל 1, פתח תקווה",
        lat: 32.089,
        lng: 34.888,
        order: 1,
        estimatedTime: "07:00",
        studentsCount: 25,
      },
      {
        stopId: "s9",
        name: "קריית ארי-אל",
        address: "אריאל שרון 10, פתח תקווה",
        lat: 32.095,
        lng: 34.877,
        order: 2,
        estimatedTime: "07:20",
        studentsCount: 11,
      },
      {
        stopId: "s10",
        name: "בית הספר המרכזי",
        address: "ביאליק 5, רמת גן",
        lat: 32.07,
        lng: 34.811,
        order: 3,
        estimatedTime: "08:00",
        studentsCount: 0,
      },
    ],
  },
  {
    id: "r4",
    name: "מסלול הרצליה",
    status: "active",
    assignedDriverUid: "d5",
    totalDistance: 31.2,
    schedule: {
      startTime: "06:45",
      endTime: "08:15",
      days: ["א'", "ב'", "ג'", "ד'", "ה'"],
    },
    stops: [
      {
        stopId: "s11",
        name: "הרצליה פיתוח",
        address: "הנביא 3, הרצליה",
        lat: 32.163,
        lng: 34.843,
        order: 1,
        estimatedTime: "06:45",
        studentsCount: 16,
      },
      {
        stopId: "s12",
        name: "רמת השרון",
        address: "ז'בוטינסקי 15, רמת השרון",
        lat: 32.143,
        lng: 34.838,
        order: 2,
        estimatedTime: "07:10",
        studentsCount: 8,
      },
      {
        stopId: "s13",
        name: "בית הספר המרכזי",
        address: "ביאליק 5, רמת גן",
        lat: 32.07,
        lng: 34.811,
        order: 3,
        estimatedTime: "07:50",
        studentsCount: 0,
      },
    ],
  },
];

export const mockLiveLocations = {
  d1: {
    lat: 32.085,
    lng: 34.778,
    speed: 42,
    nextStopIndex: 2,
    etaToNext: 8,
    timestamp: new Date(),
  },
  d2: {
    lat: 32.078,
    lng: 34.808,
    speed: 35,
    nextStopIndex: 1,
    etaToNext: 5,
    timestamp: new Date(),
  },
  d4: {
    lat: 32.091,
    lng: 34.882,
    speed: 0,
    nextStopIndex: 1,
    etaToNext: 22,
    timestamp: new Date(),
  },
  d5: {
    lat: 32.155,
    lng: 34.84,
    speed: 55,
    nextStopIndex: 1,
    etaToNext: 12,
    timestamp: new Date(),
  },
};

export const mockStats = {
  totalDrivers: 40,
  activeNow: 28,
  onlineNotDriving: 6,
  offline: 6,
  totalStudentsToday: 847,
  routesCompleted: 12,
  routesActive: 16,
  avgDelay: 3.2,
  ivrCallsToday: 234,
};
